### ISSUE TITLE
请问如何debug？

### ISSUE THREAD

**Issue by PaleNeutron** [Lotlab/FFXIV-ACT-Plugin-Template#1]
似乎是因为使用了ilmerge的原因，直接附加进程到ACT上不会触发断点

**Comment by jim-kirisame** [comment]
可能是由于我把ILMerge的合并PDB给关掉了，导致其无法输出合并后的PDB。启用方法如下：
1. 将`<ILMergeDebugInfo>false</ILMergeDebugInfo>`改成true
2. 在所有项目的属性中，将调试符号从“可跨平台移植”改为“当前平台”

在应用这些更改后，重新编译并载入插件，我这边能够在原版ACT上正常进断点。如果你正在使用整合版ACT，可以尝试下用原版ACT试试。
