### ISSUE TITLE
您好，使用模板创建生成的dll,加载到act后，悬浮窗预设没有出现在列表中。

### ISSUE THREAD

**Issue by LoveLoliii** [Lotlab/FFXIV-ACT-Plugin-Template#2]
插件列表中插件状态是inited;

使用act版本：```原版3.7.0```

使用OverlayPlugin.dll:```OverlayPlugin-0.19.23```

项目的程序集依赖直接用了绝对地址引用了act的文件

项目生成dll的信息如下：
```
E:\git\CAP\ACT-P-CAT\PluginTemplate\CatPlugin.csproj (用时 2 毫秒)。
1>Lotlab.PluginCommon -> E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon\bin\Debug\netstandard2.0\Lotlab.PluginCommon.dll
2>------ 已启动全部重新生成: 项目: Lotlab.PluginCommon.Overlay, 配置: Debug Any CPU ------
3>------ 已启动全部重新生成: 项目: Lotlab.PluginCommon.WPF, 配置: Debug Any CPU ------
4>------ 已启动全部重新生成: 项目: Lotlab.PluginCommon.FFXIV, 配置: Debug Any CPU ------
3>Lotlab.PluginCommon.WPF -> E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon.WPF\bin\Debug\net472\Lotlab.PluginCommon.WPF.dll
2>Lotlab.PluginCommon.Overlay -> E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon.Overlay\bin\Debug\net48\Lotlab.PluginCommon.Overlay.dll
4>Lotlab.PluginCommon.FFXIV -> E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon.FFXIV\bin\Debug\net472\Lotlab.PluginCommon.FFXIV.dll
5>------ 已启动全部重新生成: 项目: CatPlugin, 配置: Debug Any CPU ------
5>Merge PDBs: false
5>Merged assemblies: E:\git\CAP\ACT-P-CAT\PluginTemplate\obj\Debug\net48\CatPlugin.dll;E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon\bin\Debug\netstandard2.0\Lotlab.PluginCommon.dll;E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon.FFXIV\bin\Debug\net472\Lotlab.PluginCommon.FFXIV.dll;E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon.Overlay\bin\Debug\net48\Lotlab.PluginCommon.Overlay.dll;E:\git\CAP\ACT-P-CAT\PluginCommon\PluginCommon.WPF\bin\Debug\net472\Lotlab.PluginCommon.WPF.dll;E:\git\OverlayPlugin-0.19.23\OverlayPlugin\libs\OverlayPlugin.Common.dll
5>C:\Users\woshi\.nuget\packages\msbuild.ilmerge.task\1.1.3\build\MSBuild.ILMerge.Task.targets(88,5): warning : Specified merge order file 'E:\git\CAP\ACT-P-CAT\PluginTemplate\ILMergeOrder.txt' doesn't exist.
5>已完成生成项目“CatPlugin.csproj”的操作。
========== “全部重新生成”: 5 成功，0 失败，0已跳过 ==========
```

代码相关：[catPlugin](https://github.com/kokolokksk/ACT-P-CAT/blob/ec2e54462031182bf7156baa5dbecd03261dd60d/PluginTemplate/OverlayPlugin.cs#L27C58-L27C59)

![微信截图_20231221184615](https://github.com/Lotlab/FFXIV-ACT-Plugin-Template/assets/12725100/14eab4b1-c32c-47f8-8b59-a74feb904f21)

**Comment by jim-kirisame** [comment]
我这边也遇到了类似的问题，更新下引用的悬浮窗插件版本到最新看看？我这边更新完重新编译就解决了。

**Comment by LoveLoliii** [comment]
> 引用的悬浮窗插件版本

应该是最新的release了 【[overlayplugin-v0.19.23](https://github.com/OverlayPlugin/OverlayPlugin/releases/tag/v0.19.23)】,我去试试上个版本

**Comment by jim-kirisame** [comment]
> > 引用的悬浮窗插件版本
> 
> 应该是最新的release了 【[overlayplugin-v0.19.23](https://github.com/OverlayPlugin/OverlayPlugin/releases/tag/v0.19.23)】,我去试试上个版本

试试直接从ACT目录复制出来

**Comment by LoveLoliii** [comment]
> > > 引用的悬浮窗插件版本
> 
> > 
> 
> > 应该是最新的release了 【[overlayplugin-v0.19.23](https://github.com/OverlayPlugin/OverlayPlugin/releases/tag/v0.19.23)】,我去试试上个版本
> 
> 
> 
> 试试直接从ACT目录复制出来

好的👌

**Comment by LoveLoliii** [comment]
> > > > 引用的悬浮窗插件版本
> > 
> > 
> > > 
> > 
> > 
> > > 应该是最新的release了 【[overlayplugin-v0.19.23](https://github.com/OverlayPlugin/OverlayPlugin/releases/tag/v0.19.23)】,我去试试上个版本
> > 
> > 
> > 试试直接从ACT目录复制出来
> 
> 好的👌

最终是通过把两个继承都放在一个文件上， 参考了[Cactbot的写法](https://github.com/quisquous/cactbot/blob/2b4cbdfd7efa9725b14993b8c022f15ffa7a9c94/plugin/CactbotOverlay/PluginLoader.cs#L12) 解决了······· 我也不知道为什么这样就行了=。=

**Comment by jim-kirisame** [comment]
感觉没有区别……partial的类只不过是让你可以拆俩文件而已。感觉还是因为重新编译了才正常的。
